### ISSUE TITLE
convertElements doesn't work

### ISSUE THREAD

**Issue by chensjlv** [SmartArtsStudio/smart-svg-path#2]
First want to say good job man. I've been using this in my project. However,

https://github.com/SmartArtsStudio/smart-svg-path/blob/master/SmartSVGPath.js#L1815
is giving me this error

```
bundle.js:44939 Uncaught TypeError: svgElementCollection.item is not a function
```

**Comment by SmartArtsStudio** [comment]
Thanks for letting me know Mike, you must be hitting a code path my own project missed.

I think I see the problem and at first glance it looks like a simple fix that I'll get to on the weekend. 
In the mean time if its holding you up on line 1753:
```js
var array = SmartSVGPath._convertCollection( [svgElements], attributes, pathMethod, reversed, subPaths, precision )
```

...Is nesting the argument svgElements, which is an HTMLCollection which does have an item() function. Inside a standard array which of coarse does not. In the mean time try:

1) Removing the brackets from around the svgElements argument.
    (line 1753 inside SmartSVGPath._convertElements() )
2) Then at line 1793 inside SmartSVGPath._convertCollection()
     In the for loop statement REPLACE elementsLength with svgElementCollection.length

Let me know if this gets you going. Also it would be cool to hear what kind of project you are using it in. 
But I'll have a much closer look at it over the weekend.

**Comment by SmartArtsStudio** [comment]
**FIXED** the incorrect handling of the svgElementCollection parameter types HTMLCollection vs Array in SmartSVGPath._convertCollection(). Let me know if there are any further issues.
