### ISSUE TITLE
ERROR TypeError: Cannot read property 'reverseAbsolute' of undefined

### ISSUE THREAD

**Issue by chensjlv** [SmartArtsStudio/smart-svg-path#3]
Hi Daniel,

Thank you for your fast respond previously. Didn't get a chance to test that yet because there a new breaking change. I'm actually using your package in a typescript package. Before I can import it using
```
import { SmartSVGPath} from 'smart-svg-path';
```
But now I'm getting this error
```
ERROR TypeError: Cannot read property 'reverseAbsolute' of undefined
```
when I call
```
SmartSVGPath.reverseAbsolute(svgPathString)
```

I looked into the change and seems like you changed how you initialize the library in v1.0.3, and seems like you changed it to browser based only.

The browser should be coming from this line.
[Breaking change](https://github.com/SmartArtsStudio/smart-svg-path/compare/v1.0.3...master#diff-61680f3ac8b08d5f131c5af558629ed4R26)

There are a bunch of ways to make it work for all browser, node.js and typescript. Normally, if it works for node.js, it should work for typescript too. Looking forward to your fix, so I can upgrade :).

**Comment by SmartArtsStudio** [comment]
Sorry, yes it was suppose to expand support for all module environments not restrict it :)
I'm a little surprised but I'll look into it this week end. 
Until then the fix to the original problem simply cut paste the body of:

SmartSVGPath._convertCollection

From the latest version to the previous.

**Comment by SmartArtsStudio** [comment]
FIXED module reference not being returned. Face palm.
